# Generated by Django 4.1.4 on 2023-07-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_user_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.UUIDField(default=1, verbose_name='Реферальный код'),
            preserve_default=False,
        ),
    ]
